apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-application-using-helm
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/umerxgrid/gitops_2
    targetRevision: HEAD
    path: helm-chart-with-rollout
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true

