apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
  {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.type }}
  selector:
    app: backend
  {{- include "helm-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.backend.ports | toYaml | nindent 2 -}}
