apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.fullname" . }}-database-config
  labels:
  {{- include "helm-chart.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.databaseConfig.postgresDb | quote }}
  POSTGRES_ENDPOINT: {{ .Values.databaseConfig.postgresEndpoint | quote }}
  POSTGRES_PORT: {{ .Values.databaseConfig.postgresPort | quote }}