apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
  {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.type }}
  selector:
    app: database
  ports:
	{{- .Values.database.ports | toYaml | nindent 2 -}}
