apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}-database-secret
  labels:
  {{- include "helm-chart.labels" . | nindent 4 }}
data:
  POSTGRES_PASSWORD: {{ .Values.databaseSecret.postgresPassword }}
  POSTGRES_USER: {{ .Values.databaseSecret.postgresUser }}
type: Opaque
