apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: umerjamil16/test:backend2
        ports:
        - containerPort: 8080
        env:
          - name: POSTGRES_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: database-config
                key: POSTGRES_ENDPOINT
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                name: database-config
                key: POSTGRES_PORT
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: POSTGRES_USER
          - name: POSTGRES_NAME
            valueFrom:
              configMapKeyRef:
                name: database-config
                key: POSTGRES_DB
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: POSTGRES_PASSWORD

