apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm-chart.fullname" . }}-postgres-pv-claim
  labels:
    app: postgres
  {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.postgresPvClaim.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.postgresPvClaim.storageClass | quote }}