apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "helm-chart.fullname" . }}-postgres-pv
  labels:
    app: postgres
    type: local
  {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /var/data
  storageClassName: standard