apiVersion: v1
kind: Service
metadata:
  name: frontend-preview
  labels:
  {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.preview.type }}
  selector:
    app: frontend
  {{- include "helm-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.preview.ports | toYaml | nindent 2 -}}
